"""Build the asset catalog the frontend consumes.

`build_catalog` is pure: given the sprite manifest + icon names + an `asset_base`,
it returns the catalog JSON. With asset_base="" the URLs are same-origin /static
paths (fallback mode); with asset_base="/assets" they point at the bucket-broker
route (which redirects to a presigned Railway Bucket URL)."""
import json
import os

from aoe2x.paths import WEBAPP_DIR  # Path: <repo>/apps/website (single source of truth)

MANIFEST_PATH = str(WEBAPP_DIR / "static" / "data" / "unit_sprites.json")
ANIMS_PATH = str(WEBAPP_DIR / "static" / "data" / "unit_anims.json")
ICON_DIR = str(WEBAPP_DIR / "static" / "img" / "units")
_STATIC_PREFIX = "/static"


def load_anim_slugs() -> list:
    """Slugs that have an attack animation in the bucket (anim/<slug>.webp).
    Generated by the GIF->WebP conversion; missing file => no animations."""
    try:
        with open(ANIMS_PATH) as f:
            return json.load(f)
    except FileNotFoundError:
        return []


def _rewrite(url: str, asset_base: str) -> str:
    """/static/img/... -> {asset_base}/img/... when asset_base is set, else unchanged."""
    if not asset_base:
        return url
    return asset_base + url[len(_STATIC_PREFIX):] if url.startswith(_STATIC_PREFIX) else url


def load_manifest() -> dict:
    with open(MANIFEST_PATH) as f:
        return json.load(f)


def icon_url(name: str, asset_base: str) -> str:
    return _rewrite(f"/static/img/units/{name}.png", asset_base)


def build_catalog(manifest: dict, icon_names: list, asset_base: str, build: str,
                  anim_slugs=()) -> dict:
    sprites = {}
    for name, e in manifest.items():
        entry = {"slug": e["slug"], "w": e["w"], "h": e["h"],
                 "ratio": e["ratio"], "cat": e["cat"],
                 "url": _rewrite(e["url"], asset_base)}
        if e.get("url_blue"):
            entry["url_blue"] = _rewrite(e["url_blue"], asset_base)
        sprites[name] = entry
    icons = {name: icon_url(name, asset_base) for name in icon_names}
    # Attack animations live ONLY in the bucket (anim/<slug>.webp), so they exist
    # only in bucket mode (asset_base set). Keyed by display name via the slug.
    anims = {}
    if asset_base:
        have = set(anim_slugs)
        for name, e in manifest.items():
            if e["slug"] in have:
                anims[name] = f"{asset_base}/anim/{e['slug']}.webp"
    return {"build": build, "sprites": sprites, "icons": icons, "anims": anims}


def synthesize_local(asset_base: str = "", build: str = "local") -> dict:
    """Catalog built entirely from in-repo files (fallback / publish source)."""
    manifest = load_manifest()
    icon_names = [os.path.splitext(f)[0] for f in os.listdir(ICON_DIR)
                  if f.endswith(".png")]
    return build_catalog(manifest, icon_names, asset_base, build,
                         anim_slugs=load_anim_slugs())
