"""Derive the tapes' spawn fill order and emit src/placement-table.js.

Within a family keyed by (owner, family), the recorded layouts nest: the
N-unit layout is the first N cells of a larger layout in the same family. So
the fill order is recoverable exactly -- walk the family's layouts smallest
first and append whatever each one adds.

    python aoe2x/js_simulation/tools/derive_placement.py
"""

from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SPAWNS = ROOT / "calibration" / "fixtures" / "spawns.json"
OUTPUT = ROOT / "aoe2x" / "js_simulation" / "src" / "placement-table.js"

SIEGE = {"heavy_scorpion", "siege_onager"}
MOBILE = {"arbalester", "hand_cannoneer", "heavy_cav_archer", "imp_elite_skirm"}


def family(label: str) -> str:
    """Which spawn family a recorded matchup label belongs to.

    Mirrors resolveFamily in src/placement.js exactly; the test asserts the two
    agree on every recorded label.
    """
    left, right = re.sub(r"_r\d+$", "", label).split("__vs__")
    ranged = {unit for unit in (left, right) if unit in SIEGE or unit in MOBILE}
    if len(ranged) == 2 or (len(ranged) == 1 and left == right):
        return "rvr"
    if left in MOBILE or right in MOBILE:
        return "kite"
    if left in SIEGE or right in SIEGE:
        return "siege"
    return "waves"


def sort_key(owner: str, cell: tuple[float, float]) -> tuple[float, float]:
    """Deterministic order for cells a single recorded step adds at once.

    Cells added together are interchangeable for reproducing the recorded
    layouts -- any order within one increment yields the same set at every
    recorded size. The order only becomes observable at counts that fall
    between two recorded sizes, so it is fixed here: front rank first, then
    left to right.
    """
    x, y = cell
    return (-y if owner == "2" else y, x)


def main() -> None:
    spawns = json.loads(SPAWNS.read_text())
    families: dict[tuple[str, str], list[frozenset]] = defaultdict(list)
    side_layouts = 0
    for label, sides in spawns.items():
        group = family(label)
        for owner in ("2", "3"):
            points = frozenset(tuple(point) for point in sides[owner])
            families[(owner, group)].append(points)
            side_layouts += 1

    table: dict[str, list[list[float]]] = {}
    exact = 0
    residue: list[dict] = []
    for (owner, group), layouts in sorted(families.items()):
        order: list[tuple[float, float]] = []
        seen: set[tuple[float, float]] = set()
        for layout in sorted(layouts, key=len):
            added = sorted(layout - seen, key=lambda c: sort_key(owner, c))
            order.extend(added)
            seen.update(added)
        for layout in layouts:
            if set(order[: len(layout)]) == set(layout):
                exact += 1
            else:
                residue.append({
                    "owner": owner,
                    "family": group,
                    "count": len(layout),
                    "missing": sorted(map(list, set(layout) - set(order[: len(layout)]))),
                    "extra": sorted(map(list, set(order[: len(layout)]) - set(layout))),
                })
        table[f"{owner}@{group}"] = [list(cell) for cell in order]

    print(f"side-layouts {side_layouts}  exact {exact}  residue {len(residue)}")
    for row in residue:
        print("  RESIDUE", row)
    for key, cells in sorted(table.items()):
        print(f"  {key}: {len(cells)} cells")

    body = json.dumps(table, indent=2, sort_keys=True)
    provenance = json.dumps({
        "source": "calibration/fixtures/spawns.json",
        "layouts": len(spawns),
        "sideLayouts": side_layouts,
        "exact": exact,
        "residue": len(residue),
    }, indent=2, sort_keys=True)
    OUTPUT.write_text(
        "// GENERATED by tools/derive_placement.py -- do not edit by hand.\n"
        "//\n"
        "// Ordered spawn cells per family, keyed \"<owner>@<family>\". Take the\n"
        "// first N cells for an N-unit army. The key is (owner, family) and\n"
        "// nothing else: band edge is an output of the fill order, not an input.\n"
        f"export const PLACEMENT_TABLE = Object.freeze({body});\n"
        "\n"
        f"export const PLACEMENT_PROVENANCE = Object.freeze({provenance});\n",
        encoding="utf8",
    )


if __name__ == "__main__":
    main()
