"""Phase-0 build: publish unit sprites into the website (decision C1) + manifest.

For every unit that has a red idle sprite (graphics/units/<slug>/<slug>_idle_dir06_dat4x.png):
  * copy red  -> apps/website/static/img/unit_sprites/<slug>.png
  * copy blue -> apps/website/static/img/unit_sprites/<slug>_blue.png   (if generated)
  each downscaled so the longer side <= MAX_SIDE (keeps web payload small; display
  sizes are 24-88px and the sim draws at ~30-60px, so this is still oversampled).

Also writes the manifest the frontend reads:
  apps/website/static/data/unit_sprites.json   keyed by unit DISPLAY NAME:
    "Knight": {slug, w, h, ratio, cat, url, url_blue}
  cat = square (<=1.5) | borderline (1.5-1.8) | extreme (>1.8).  Phase 1 only
  USES cat=="square"; the rest are published but the frontend falls back to the
  old portrait until promoted (just flip their cat / the frontend gate).

Run with conda base python (numpy + Pillow):
  C:/Users/ddk22/miniconda3/python.exe graphics/units/sync_web_sprites.py
"""
import os, sys, json, argparse
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
from PIL import Image
from build_unit_assets import UNITS_DIR, IDLE_DIR_ANGLE, NAME_FORCE_ID, NAME_DROP
from build_icons import slugify
from aoe2x.extract.extract_units import UNIT_NAMES

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
WEB = os.path.join(ROOT, 'apps', 'website', 'static')
SPRITE_OUT = os.path.join(WEB, 'img', 'unit_sprites')
MANIFEST = os.path.join(WEB, 'data', 'unit_sprites.json')       # tooling copy
MANIFEST_JS = os.path.join(WEB, 'js', 'unit_sprites.js')         # browser copy (sync load)
MAX_SIDE = 384
URL_BASE = '/static/img/unit_sprites'


def categorize(ratio):
    if ratio <= 1.5:
        return 'square'
    if ratio <= 1.8:
        return 'borderline'
    return 'extreme'


def downscaled(path):
    im = Image.open(path).convert('RGBA')
    w, h = im.size
    if max(w, h) > MAX_SIDE:
        s = MAX_SIDE / max(w, h)
        im = im.resize((round(w * s), round(h * s)), Image.LANCZOS)
    return im


def corrected_name_slug():
    """display name -> slug, with the graphics-roster corrections applied."""
    out = {}
    for uid, name in UNIT_NAMES.items():
        if name in NAME_DROP or name in out:
            continue
        out[name] = slugify(name)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--max-side', type=int, default=MAX_SIDE)
    args = ap.parse_args()
    max_side = args.max_side

    os.makedirs(SPRITE_OUT, exist_ok=True)
    os.makedirs(os.path.dirname(MANIFEST), exist_ok=True)

    manifest = {}
    copied = blue = 0
    for name, slug in corrected_name_slug().items():
        red = os.path.join(UNITS_DIR, slug, f'{slug}_idle_dir{IDLE_DIR_ANGLE:02d}_dat4x.png')
        if not os.path.exists(red):
            continue                                  # naval / unresolved -> no sprite
        w, h = Image.open(red).size
        ratio = round(max(w, h) / min(w, h), 3)
        cat = categorize(ratio)

        im = Image.open(red).convert('RGBA')
        if max(w, h) > max_side:
            s = max_side / max(w, h)
            im = im.resize((round(w * s), round(h * s)), Image.LANCZOS)
        im.save(os.path.join(SPRITE_OUT, f'{slug}.png'))
        copied += 1

        entry = {'slug': slug, 'w': im.width, 'h': im.height, 'ratio': ratio,
                 'cat': cat, 'url': f'{URL_BASE}/{slug}.png'}

        bpath = os.path.join(UNITS_DIR, slug, f'{slug}_idle_dir{IDLE_DIR_ANGLE:02d}_dat4x_blue.png')
        if os.path.exists(bpath):
            bim = downscaled(bpath)
            bim.save(os.path.join(SPRITE_OUT, f'{slug}_blue.png'))
            entry['url_blue'] = f'{URL_BASE}/{slug}_blue.png'
            blue += 1

        manifest[name] = entry

    json.dump(manifest, open(MANIFEST, 'w'), indent=1, sort_keys=True)
    with open(MANIFEST_JS, 'w', encoding='utf-8') as f:
        f.write('/* GENERATED by graphics/units/sync_web_sprites.py — do not edit by hand.\n'
                '   Unit display name -> red/blue idle-sprite icon. Used by spriteFor()\n'
                '   in constants.js (falls back to the portrait when a unit has no\n'
                '   square sprite). Regenerate after re-running the sprite pipeline. */\n')
        f.write('const UNIT_SPRITES = ')
        f.write(json.dumps(manifest, indent=1, sort_keys=True))
        f.write(';\n')
    cats = {}
    for e in manifest.values():
        cats[e['cat']] = cats.get(e['cat'], 0) + 1
    print(f'published {copied} red + {blue} blue sprites -> {SPRITE_OUT}')
    print(f'manifest: {len(manifest)} units -> {MANIFEST}')
    print(f'  by category: {cats}')
    no_blue = [n for n, e in manifest.items() if 'url_blue' not in e]
    if no_blue:
        print(f'  {len(no_blue)} without a blue variant (run build_blue_sprites.py): '
              f'{sorted(e["slug"] for n, e in manifest.items() if "url_blue" not in e)[:10]} ...')


if __name__ == '__main__':
    main()
